import os
import random
import re
from datetime import UTC, date, datetime, time, timedelta
from uuid import NAMESPACE_URL, UUID, uuid5

NS = uuid5(NAMESPACE_URL, "tourism-shopping-assistant-poc")


def stable_id(kind: str, value: str) -> UUID:
    return uuid5(NS, f"{kind}:{value}")


PRODUCTS = [
    {
        "slug": "hoi-an-ancient-town-walking-tour",
        "title": "Hoi An Ancient Town Heritage Walk",
        "destination": "Hoi An",
        "category": "Guided tour",
        "sub": ["walking tour", "heritage"],
        "tags": ["history", "architecture", "culture", "photography"],
        "summary": "A small-group walk through lantern lanes, merchant houses and the Japanese Bridge.",
        "description": "Explore Hoi An's trading-port history with a licensed local guide, heritage admissions and a lantern-making demonstration.",
        "io": "outdoor",
        "duration": 180,
        "price": 690000,
        "child": 390000,
        "times": [8, 14, 17],
        "rating": 4.8,
        "reviews": 342,
        "family": True,
        "access": ["step-free route available", "rest stops"],
        "lat": 15.877,
        "lon": 108.326,
    },
    {
        "slug": "hoi-an-lantern-making-class",
        "title": "Hoi An Lantern-Making Workshop",
        "destination": "Hoi An",
        "category": "Activity or class",
        "sub": ["craft class", "indoor"],
        "tags": ["crafts", "family", "culture", "rainy day"],
        "summary": "Make a foldable silk lantern with a local artisan and take it home.",
        "description": "A relaxed hands-on workshop covering bamboo framing, silk fitting and Hoi An lantern traditions. Materials and tea are included.",
        "io": "indoor",
        "duration": 120,
        "price": 520000,
        "child": 420000,
        "times": [9, 13, 16],
        "rating": 4.9,
        "reviews": 214,
        "family": True,
        "access": ["wheelchair accessible", "accessible restroom"],
        "lat": 15.879,
        "lon": 108.329,
    },
    {
        "slug": "hoi-an-evening-food-tour",
        "title": "Hoi An Evening Street Food Tour",
        "destination": "Hoi An",
        "category": "Food experience",
        "sub": ["food tour", "walking tour"],
        "tags": ["food", "nightlife", "local life"],
        "summary": "Taste cao lau, white rose dumplings and market snacks with a local food guide.",
        "description": "Visit family-run stalls and hidden courtyards for eight tastings, with dietary needs handled when advised in advance.",
        "io": "outdoor",
        "duration": 210,
        "price": 980000,
        "child": 620000,
        "times": [17, 18],
        "rating": 4.9,
        "reviews": 481,
        "family": True,
        "access": ["moderate walking", "dietary accommodations"],
        "lat": 15.876,
        "lon": 108.327,
    },
    {
        "slug": "cam-thanh-coconut-forest-basket-boat",
        "title": "Cam Thanh Coconut Forest Basket Boat",
        "destination": "Hoi An",
        "category": "Activity or class",
        "sub": ["boat ride", "nature"],
        "tags": ["nature", "family", "river", "local life"],
        "summary": "Glide through nipa palms by basket boat with fishing demonstrations.",
        "description": "A gentle basket-boat trip through Bay Mau coconut forest including hotel-area transfer and a local snack.",
        "io": "outdoor",
        "duration": 150,
        "price": 460000,
        "child": 300000,
        "times": [8, 10, 14, 16],
        "rating": 4.6,
        "reviews": 526,
        "family": True,
        "access": ["transfer assistance", "life jackets"],
        "lat": 15.845,
        "lon": 108.385,
    },
    {
        "slug": "my-son-sanctuary-sunrise-tour",
        "title": "My Son Sanctuary Sunrise Tour",
        "destination": "Hoi An",
        "category": "Day trip",
        "sub": ["archaeology", "temple tour"],
        "tags": ["history", "unesco", "photography", "culture"],
        "summary": "See the Cham temple towers in cool morning light before the crowds.",
        "description": "Early minibus transfer, English guide, admission and breakfast banh mi are included. Uneven paths require steady mobility.",
        "io": "outdoor",
        "duration": 330,
        "price": 850000,
        "child": 520000,
        "times": [5],
        "rating": 4.8,
        "reviews": 397,
        "family": False,
        "access": ["uneven ground", "rest stops"],
        "lat": 15.765,
        "lon": 108.124,
    },
    {
        "slug": "cham-islands-snorkeling-day-trip",
        "title": "Cham Islands Snorkeling Day Trip",
        "destination": "Hoi An",
        "category": "Day trip",
        "sub": ["snorkeling", "island tour"],
        "tags": ["nature", "adventure", "beach", "marine life"],
        "summary": "Speedboat to Cu Lao Cham with guided snorkeling, beach time and lunch.",
        "description": "A full-day island escape with marine guide, equipment, seafood lunch and Cua Dai transfers. Weather dependent.",
        "io": "outdoor",
        "duration": 480,
        "price": 1450000,
        "child": 950000,
        "times": [8],
        "rating": 4.5,
        "reviews": 288,
        "family": True,
        "access": ["swimming required", "life jackets"],
        "lat": 15.953,
        "lon": 108.51,
    },
    {
        "slug": "hoi-an-memories-show",
        "title": "Hoi An Memories Show Ticket",
        "destination": "Hoi An",
        "category": "Entertainment experience",
        "sub": ["live show", "open-air theatre"],
        "tags": ["culture", "evening", "family", "performance"],
        "summary": "A large-scale outdoor performance tracing four centuries of Hoi An history.",
        "description": "Reserved seating and mobile voucher entry for the riverside spectacle with hundreds of performers.",
        "io": "outdoor",
        "duration": 90,
        "price": 800000,
        "child": 550000,
        "times": [20],
        "rating": 4.7,
        "reviews": 612,
        "family": True,
        "access": ["wheelchair accessible", "accessible seating"],
        "lat": 15.875,
        "lon": 108.347,
    },
    {
        "slug": "hoi-an-thu-bon-sunset-cruise",
        "title": "Thu Bon River Sunset Cruise",
        "destination": "Hoi An",
        "category": "Cruise",
        "sub": ["river cruise", "sunset"],
        "tags": ["romance", "photography", "evening", "river"],
        "summary": "A quiet wooden-boat cruise with sunset views and floating lanterns.",
        "description": "Sail from the old town into the Thu Bon estuary with a welcome drink and one biodegradable lantern.",
        "io": "outdoor",
        "duration": 90,
        "price": 620000,
        "child": 380000,
        "times": [17],
        "rating": 4.6,
        "reviews": 174,
        "family": True,
        "access": ["boarding assistance", "life jackets"],
        "lat": 15.874,
        "lon": 108.334,
    },
    {
        "slug": "da-nang-ba-na-hills-golden-bridge",
        "title": "Ba Na Hills and Golden Bridge Day Tour",
        "destination": "Da Nang",
        "category": "Day trip",
        "sub": ["theme park", "cable car"],
        "tags": ["family", "mountains", "photography", "theme park"],
        "summary": "Cable-car admission, Golden Bridge and French Village with return transport.",
        "description": "A guided full day at Ba Na Hills including cable cars, buffet lunch and Da Nang or Hoi An pickup.",
        "io": "mixed",
        "duration": 600,
        "price": 1850000,
        "child": 1450000,
        "times": [7],
        "rating": 4.7,
        "reviews": 1044,
        "family": True,
        "access": ["wheelchair accessible areas", "cable car"],
        "lat": 15.996,
        "lon": 107.996,
    },
    {
        "slug": "da-nang-marble-mountains-lady-buddha",
        "title": "Marble Mountains and Lady Buddha Tour",
        "destination": "Da Nang",
        "category": "Guided tour",
        "sub": ["temple tour", "scenic"],
        "tags": ["history", "spirituality", "photography"],
        "summary": "Caves, pagodas and panoramic coastal views with a local guide.",
        "description": "Half-day shared tour of Marble Mountains, stone-carving village and Linh Ung Pagoda. Elevator ticket included.",
        "io": "outdoor",
        "duration": 300,
        "price": 760000,
        "child": 480000,
        "times": [8, 14],
        "rating": 4.7,
        "reviews": 433,
        "family": True,
        "access": ["elevator available", "many steps at viewpoints"],
        "lat": 16.003,
        "lon": 108.264,
    },
    {
        "slug": "da-nang-dragon-bridge-night-cruise",
        "title": "Da Nang Han River Night Cruise",
        "destination": "Da Nang",
        "category": "Cruise",
        "sub": ["river cruise", "night tour"],
        "tags": ["nightlife", "city lights", "family", "river"],
        "summary": "Cruise beneath Da Nang's illuminated bridges with weekend fire-show views.",
        "description": "A comfortable evening cruise with reserved seating, fruit and city commentary.",
        "io": "outdoor",
        "duration": 75,
        "price": 420000,
        "child": 260000,
        "times": [19, 20],
        "rating": 4.5,
        "reviews": 365,
        "family": True,
        "access": ["boarding assistance", "accessible restroom"],
        "lat": 16.064,
        "lon": 108.227,
    },
    {
        "slug": "da-nang-airport-private-transfer",
        "title": "Da Nang Airport Private Transfer",
        "destination": "Da Nang",
        "category": "Transport ticket",
        "sub": ["airport transfer", "private car"],
        "tags": ["transport", "convenience", "family"],
        "summary": "Private air-conditioned transfer between Da Nang airport, city or Hoi An.",
        "description": "Flight-tracked pickup, meet-and-greet and fixed price for up to four passengers with luggage.",
        "io": "indoor",
        "duration": 60,
        "price": 480000,
        "child": 0,
        "times": [6, 9, 12, 15, 18, 21],
        "rating": 4.8,
        "reviews": 721,
        "family": True,
        "access": ["child seat on request", "folding wheelchair accepted"],
        "lat": 16.056,
        "lon": 108.202,
    },
    {
        "slug": "da-nang-vietnamese-cooking-class",
        "title": "Da Nang Market and Vietnamese Cooking Class",
        "destination": "Da Nang",
        "category": "Activity or class",
        "sub": ["cooking class", "market tour"],
        "tags": ["food", "culture", "rainy day", "family"],
        "summary": "Shop at a local market then cook four central Vietnamese dishes.",
        "description": "An air-conditioned hands-on kitchen class with market visit, recipe booklet and vegetarian alternatives.",
        "io": "indoor",
        "duration": 240,
        "price": 1100000,
        "child": 750000,
        "times": [9, 15],
        "rating": 4.9,
        "reviews": 192,
        "family": True,
        "access": ["wheelchair accessible", "dietary accommodations"],
        "lat": 16.059,
        "lon": 108.222,
    },
    {
        "slug": "son-tra-peninsula-jeep-tour",
        "title": "Son Tra Peninsula Vintage Jeep Tour",
        "destination": "Da Nang",
        "category": "Guided tour",
        "sub": ["jeep tour", "wildlife"],
        "tags": ["adventure", "nature", "photography", "wildlife"],
        "summary": "Explore forest roads, viewpoints and hidden beaches in a restored open-top jeep.",
        "description": "A half-day private jeep route with a naturalist guide, picnic drink and chances to spot red-shanked doucs.",
        "io": "outdoor",
        "duration": 270,
        "price": 1350000,
        "child": 900000,
        "times": [7, 14],
        "rating": 4.8,
        "reviews": 126,
        "family": False,
        "access": ["high vehicle step", "bumpy roads"],
        "lat": 16.119,
        "lon": 108.277,
    },
    {
        "slug": "hue-imperial-city-day-tour",
        "title": "Hue Imperial City and Royal Tombs Day Tour",
        "destination": "Hue",
        "category": "Day trip",
        "sub": ["heritage", "palace tour"],
        "tags": ["history", "unesco", "architecture", "culture"],
        "summary": "Discover the Citadel, Thien Mu Pagoda and Nguyen royal tombs.",
        "description": "Full-day guided heritage circuit with admissions, dragon-boat ride, lunch and central Hue pickup.",
        "io": "mixed",
        "duration": 540,
        "price": 1250000,
        "child": 780000,
        "times": [8],
        "rating": 4.8,
        "reviews": 589,
        "family": True,
        "access": ["wheelchair accessible sections", "rest stops"],
        "lat": 16.463,
        "lon": 107.59,
    },
    {
        "slug": "hue-perfume-river-dinner-cruise",
        "title": "Perfume River Dinner Cruise",
        "destination": "Hue",
        "category": "Cruise",
        "sub": ["dinner cruise", "traditional music"],
        "tags": ["food", "music", "romance", "evening"],
        "summary": "Hue cuisine and live royal court music aboard a dragon boat.",
        "description": "A set-menu dinner cruise on the Perfume River with reserved table and traditional ca Hue performance.",
        "io": "mixed",
        "duration": 120,
        "price": 880000,
        "child": 560000,
        "times": [19],
        "rating": 4.5,
        "reviews": 203,
        "family": True,
        "access": ["boarding assistance", "dietary accommodations"],
        "lat": 16.466,
        "lon": 107.592,
    },
    {
        "slug": "hue-royal-spa-package",
        "title": "Hue Royal Herbal Spa Ritual",
        "destination": "Hue",
        "category": "Open-dated voucher",
        "sub": ["spa", "wellness"],
        "tags": ["wellness", "relaxation", "rainy day", "couples"],
        "summary": "A 90-minute herbal foot soak and full-body massage inspired by royal remedies.",
        "description": "Private treatment room, herbal tea and flexible open-dated mobile voucher valid for 30 days.",
        "io": "indoor",
        "duration": 90,
        "price": 790000,
        "child": 790000,
        "times": [10, 12, 14, 16, 18, 20],
        "rating": 4.9,
        "reviews": 167,
        "family": False,
        "access": ["wheelchair accessible", "private room"],
        "lat": 16.465,
        "lon": 107.595,
        "validity": "OPEN_DATED",
    },
    {
        "slug": "hoi-an-da-nang-shuttle-pass",
        "title": "Hoi An–Da Nang Flexible Shuttle Pass",
        "destination": "Hoi An",
        "category": "Transport ticket",
        "sub": ["shuttle", "day pass"],
        "tags": ["transport", "budget", "convenience"],
        "summary": "One-day hop-on shuttle connections between Hoi An, beaches and central Da Nang.",
        "description": "Mobile day pass with six scheduled departures, air conditioning and one standard luggage item.",
        "io": "indoor",
        "duration": 60,
        "price": 320000,
        "child": 220000,
        "times": [7, 9, 11, 14, 17, 20],
        "rating": 4.4,
        "reviews": 98,
        "family": True,
        "access": ["folding wheelchair accepted", "child seats"],
        "lat": 15.88,
        "lon": 108.328,
    },
]

IMAGE_SLUGS = {
    "hoi-an-ancient-town-walking-tour": "hoi-an-lantern-evening",
    "hoi-an-lantern-making-class": "hoi-an-cooking-class",
    "hoi-an-evening-food-tour": "da-nang-street-food",
    "cam-thanh-coconut-forest-basket-boat": "basket-boat-coconut-forest",
    "my-son-sanctuary-sunrise-tour": "my-son-sanctuary-sunrise",
    "cham-islands-snorkeling-day-trip": "cham-islands-snorkeling",
    "hoi-an-memories-show": "hoi-an-lantern-evening",
    "hoi-an-thu-bon-sunset-cruise": "han-river-sunset-cruise",
    "da-nang-ba-na-hills-golden-bridge": "ba-na-hills-golden-bridge",
    "da-nang-marble-mountains-lady-buddha": "marble-mountains-caves",
    "da-nang-dragon-bridge-night-cruise": "han-river-sunset-cruise",
    "da-nang-airport-private-transfer": "son-tra-wildlife-sunrise",
    "da-nang-vietnamese-cooking-class": "hoi-an-cooking-class",
    "son-tra-peninsula-jeep-tour": "son-tra-wildlife-sunrise",
    "hue-imperial-city-day-tour": "hue-imperial-day-trip",
    "hue-perfume-river-dinner-cruise": "han-river-sunset-cruise",
    "hue-royal-spa-package": "vietnamese-spa-ritual",
    "hoi-an-da-nang-shuttle-pass": "ba-na-hills-golden-bridge",
}

DESTINATIONS = [
    {
        "name": "Hanoi",
        "lat": 21.0285,
        "lon": 105.8542,
        "focus": ["Old Quarter", "Hoan Kiem", "West Lake", "French Quarter"],
        "themes": ["city", "culture", "food"],
    },
    {
        "name": "Ha Long",
        "lat": 20.9101,
        "lon": 107.1839,
        "focus": ["Ha Long Bay", "Lan Ha Bay", "Bai Tu Long", "Cat Ba"],
        "themes": ["coast", "nature", "cruise"],
    },
    {
        "name": "Ninh Binh",
        "lat": 20.2506,
        "lon": 105.9745,
        "focus": ["Trang An", "Tam Coc", "Hoa Lu", "Mua Cave"],
        "themes": ["river", "nature", "culture"],
    },
    {
        "name": "Sapa",
        "lat": 22.3364,
        "lon": 103.8438,
        "focus": ["Muong Hoa", "Fansipan", "Ta Van", "Cat Cat"],
        "themes": ["mountain", "nature", "culture"],
    },
    {
        "name": "Hue",
        "lat": 16.4637,
        "lon": 107.5909,
        "focus": ["Imperial City", "Perfume River", "Thien Mu", "Royal Tombs"],
        "themes": ["culture", "river", "food"],
    },
    {
        "name": "Da Nang",
        "lat": 16.0544,
        "lon": 108.2022,
        "focus": ["My Khe", "Son Tra", "Marble Mountains", "Han River"],
        "themes": ["coast", "city", "nature"],
    },
    {
        "name": "Hoi An",
        "lat": 15.8801,
        "lon": 108.338,
        "focus": ["Ancient Town", "Cam Thanh", "An Bang", "Tra Que"],
        "themes": ["culture", "river", "food"],
    },
    {
        "name": "Quy Nhon",
        "lat": 13.782,
        "lon": 109.219,
        "focus": ["Ky Co", "Eo Gio", "Phuong Mai", "Bai Xep"],
        "themes": ["coast", "nature", "food"],
    },
    {
        "name": "Nha Trang",
        "lat": 12.2388,
        "lon": 109.1967,
        "focus": ["Hon Mun", "Nha Trang Bay", "Po Nagar", "Hon Chong"],
        "themes": ["coast", "island", "wellness"],
    },
    {
        "name": "Da Lat",
        "lat": 11.9404,
        "lon": 108.4583,
        "focus": ["Tuyen Lam", "Lang Biang", "Cau Dat", "Da Lat Market"],
        "themes": ["mountain", "nature", "food"],
    },
    {
        "name": "Ho Chi Minh City",
        "lat": 10.7769,
        "lon": 106.7009,
        "focus": ["District 1", "Cholon", "Saigon River", "Cu Chi"],
        "themes": ["city", "culture", "food"],
    },
    {
        "name": "Mekong Delta",
        "lat": 10.0452,
        "lon": 105.7469,
        "focus": ["Cai Be", "Ben Tre", "My Tho", "Vinh Long"],
        "themes": ["river", "nature", "food"],
    },
    {
        "name": "Can Tho",
        "lat": 10.0452,
        "lon": 105.7469,
        "focus": ["Cai Rang", "Ninh Kieu", "Phong Dien", "Son Islet"],
        "themes": ["river", "city", "food"],
    },
    {
        "name": "Phu Quoc",
        "lat": 10.2899,
        "lon": 103.984,
        "focus": ["An Thoi", "Khem Beach", "Cua Can", "Ganh Dau"],
        "themes": ["island", "coast", "nature"],
    },
    {
        "name": "Mui Ne",
        "lat": 10.9333,
        "lon": 108.2833,
        "focus": ["White Dunes", "Red Dunes", "Fishing Village", "Fairy Stream"],
        "themes": ["coast", "nature", "adventure"],
    },
    {
        "name": "Con Dao",
        "lat": 8.6833,
        "lon": 106.6,
        "focus": ["Dam Trau", "Bay Canh", "Con Son", "Hon Cau"],
        "themes": ["island", "nature", "culture"],
    },
    {
        "name": "Vung Tau",
        "lat": 10.4114,
        "lon": 107.1362,
        "focus": ["Back Beach", "Front Beach", "Nui Lon", "Long Hai"],
        "themes": ["coast", "city", "food"],
    },
    {
        "name": "Buon Ma Thuot",
        "lat": 12.6667,
        "lon": 108.05,
        "focus": ["Dray Nur", "Lak Lake", "Coffee Village", "Yok Don"],
        "themes": ["nature", "coffee", "culture"],
    },
]

EXPERIENCE_TEMPLATES = [
    {
        "key": "heritage-walk",
        "title": "Heritage Story Walk",
        "category": "Culture",
        "sub": ["heritage", "walking tour"],
        "tags": ["history", "architecture", "local guide"],
        "summary": "Explore landmark stories, hidden lanes and everyday local life with a licensed guide.",
        "io": "outdoor",
        "duration": 180,
        "price": 620000,
        "times": [8, 15],
        "family": True,
        "image": "hoi-an-lantern-evening",
    },
    {
        "key": "food-evening",
        "title": "Street Food Evening",
        "category": "Food",
        "sub": ["food tour", "night tour"],
        "tags": ["food", "market", "local life"],
        "summary": "Taste regional favourites at family-run stalls with a local food storyteller.",
        "io": "mixed",
        "duration": 210,
        "price": 880000,
        "times": [17, 18],
        "family": True,
        "image": "da-nang-street-food",
    },
    {
        "key": "cooking-class",
        "title": "Market-to-Table Cooking Class",
        "category": "Food",
        "sub": ["cooking class", "market"],
        "tags": ["cooking", "food", "rainy day"],
        "summary": "Shop for fresh ingredients and prepare a regional menu in a welcoming local kitchen.",
        "io": "indoor",
        "duration": 240,
        "price": 1050000,
        "times": [9, 15],
        "family": True,
        "image": "hoi-an-cooking-class",
    },
    {
        "key": "sunrise-photo",
        "title": "Sunrise Photography Journey",
        "category": "Nature",
        "sub": ["photography", "sunrise"],
        "tags": ["sunrise", "photography", "scenery"],
        "summary": "Reach a signature viewpoint in the soft morning light with practical photo guidance.",
        "io": "outdoor",
        "duration": 240,
        "price": 920000,
        "times": [5],
        "family": False,
        "image": "son-tra-wildlife-sunrise",
    },
    {
        "key": "river-cruise",
        "title": "Sunset Boutique Cruise",
        "category": "Water",
        "sub": ["cruise", "sunset"],
        "tags": ["river", "sunset", "romance"],
        "summary": "Slow down on the water with skyline or countryside views and a welcome drink.",
        "io": "outdoor",
        "duration": 120,
        "price": 760000,
        "times": [17],
        "family": True,
        "image": "han-river-sunset-cruise",
    },
    {
        "key": "family-pass",
        "title": "Family Discovery Pass",
        "category": "Family",
        "sub": ["family pass", "admission"],
        "tags": ["family", "children", "flexible"],
        "summary": "A flexible bundle of easy activities designed for families exploring at their own pace.",
        "io": "mixed",
        "duration": 300,
        "price": 790000,
        "times": [9, 13],
        "family": True,
        "image": "basket-boat-coconut-forest",
    },
    {
        "key": "nature-day",
        "title": "Nature & Village Day",
        "category": "Day trip",
        "sub": ["nature", "village"],
        "tags": ["nature", "local life", "lunch"],
        "summary": "Spend a day among landscapes, craft villages and a relaxed regional lunch.",
        "io": "outdoor",
        "duration": 480,
        "price": 1450000,
        "times": [7],
        "family": True,
        "image": "my-son-sanctuary-sunrise",
    },
    {
        "key": "wellness",
        "title": "Herbal Wellness Ritual",
        "category": "Wellness",
        "sub": ["spa", "open-dated voucher"],
        "tags": ["wellness", "relaxation", "rainy day"],
        "summary": "Unwind with a private herbal treatment and flexible open-dated mobile voucher.",
        "io": "indoor",
        "duration": 120,
        "price": 820000,
        "times": [10, 13, 16, 19],
        "family": False,
        "validity": "OPEN_DATED",
        "image": "vietnamese-spa-ritual",
    },
    {
        "key": "transfer",
        "title": "Private Arrival Transfer",
        "category": "Transport",
        "sub": ["private transfer", "airport"],
        "tags": ["transport", "convenience", "family"],
        "summary": "A flight-tracked private transfer with a friendly local driver and fixed pricing.",
        "io": "indoor",
        "duration": 75,
        "price": 520000,
        "times": [6, 9, 12, 15, 18, 21],
        "family": True,
        "image": "ba-na-hills-golden-bridge",
    },
    {
        "key": "craft-class",
        "title": "Traditional Craft Workshop",
        "category": "Culture",
        "sub": ["craft class", "artisan"],
        "tags": ["crafts", "culture", "rainy day"],
        "summary": "Learn a regional craft from an artisan and leave with something made by hand.",
        "io": "indoor",
        "duration": 150,
        "price": 610000,
        "times": [9, 14, 17],
        "family": True,
        "image": "hoi-an-cooking-class",
    },
    {
        "key": "cycling",
        "title": "Countryside Cycling Escape",
        "category": "Nature",
        "sub": ["cycling", "countryside"],
        "tags": ["cycling", "nature", "village"],
        "summary": "Ride quiet backroads through farms and villages with frequent scenic stops.",
        "io": "outdoor",
        "duration": 270,
        "price": 860000,
        "times": [7, 14],
        "family": True,
        "image": "son-tra-wildlife-sunrise",
    },
    {
        "key": "night-show",
        "title": "Culture & Light Night Show",
        "category": "Culture",
        "sub": ["live show", "evening"],
        "tags": ["performance", "culture", "evening"],
        "summary": "Reserved admission to a colourful evening performance inspired by local stories.",
        "io": "mixed",
        "duration": 100,
        "price": 690000,
        "times": [19, 20],
        "family": True,
        "image": "hoi-an-lantern-evening",
    },
    {
        "key": "coffee",
        "title": "Vietnamese Coffee Lab",
        "category": "Food",
        "sub": ["coffee workshop", "tasting"],
        "tags": ["coffee", "workshop", "rainy day"],
        "summary": "Taste regional beans and learn phin, egg and coconut coffee techniques.",
        "io": "indoor",
        "duration": 120,
        "price": 480000,
        "times": [10, 14, 17],
        "family": False,
        "image": "da-nang-street-food",
    },
    {
        "key": "boat-nature",
        "title": "Small-Boat Nature Discovery",
        "category": "Water",
        "sub": ["boat ride", "wildlife"],
        "tags": ["boat", "nature", "wildlife"],
        "summary": "Travel by small boat through a distinctive local ecosystem with a nature guide.",
        "io": "outdoor",
        "duration": 210,
        "price": 940000,
        "times": [7, 14],
        "family": True,
        "image": "basket-boat-coconut-forest",
    },
    {
        "key": "premium-day",
        "title": "Signature Highlights Private Day",
        "category": "Day trip",
        "sub": ["private tour", "highlights"],
        "tags": ["private", "highlights", "flexible"],
        "summary": "A private, flexible day connecting the destination's essential sights and flavours.",
        "io": "mixed",
        "duration": 540,
        "price": 2450000,
        "times": [8],
        "family": True,
        "image": "hue-imperial-day-trip",
    },
    {
        "key": "adventure",
        "title": "Scenic Adventure Route",
        "category": "Day trip",
        "sub": ["adventure", "scenic"],
        "tags": ["adventure", "views", "active"],
        "summary": "An active guided route connecting viewpoints, trails and lesser-known local stops.",
        "io": "outdoor",
        "duration": 360,
        "price": 1280000,
        "times": [7, 13],
        "family": False,
        "image": "marble-mountains-caves",
    },
    {
        "key": "evening-bites",
        "title": "Evening Bites & Hidden Bars",
        "category": "Food",
        "sub": ["food tour", "nightlife"],
        "tags": ["food", "nightlife", "local host"],
        "summary": "Pair regional bites with atmospheric local venues on a social small-group evening.",
        "io": "mixed",
        "duration": 210,
        "price": 980000,
        "times": [18],
        "family": False,
        "image": "da-nang-street-food",
    },
    {
        "key": "open-bus",
        "title": "Flexible Explorer Shuttle",
        "category": "Transport",
        "sub": ["shuttle", "day pass"],
        "tags": ["transport", "budget", "flexible"],
        "summary": "A mobile day pass linking the destination's most useful visitor stops.",
        "io": "indoor",
        "duration": 90,
        "price": 340000,
        "times": [7, 9, 11, 14, 17],
        "family": True,
        "image": "ba-na-hills-golden-bridge",
    },
    {
        "key": "rainy-day",
        "title": "Rainy-Day Culture Bundle",
        "category": "Family",
        "sub": ["indoor pass", "museum"],
        "tags": ["indoor", "rainy day", "culture", "family"],
        "summary": "A weather-proof bundle of indoor culture, tasting and hands-on activities.",
        "io": "indoor",
        "duration": 300,
        "price": 830000,
        "times": [9, 13],
        "family": True,
        "image": "hoi-an-cooking-class",
    },
    {
        "key": "island-water",
        "title": "Island & Clear-Water Day",
        "category": "Water",
        "sub": ["island tour", "snorkeling"],
        "tags": ["island", "beach", "snorkeling"],
        "summary": "A bright day on the water with swimming, a beach stop and an easy local lunch.",
        "io": "outdoor",
        "duration": 450,
        "price": 1580000,
        "times": [8],
        "family": True,
        "image": "cham-islands-snorkeling",
    },
]


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")


def generated_sources(target_count: int) -> list[dict]:
    generated: list[dict] = []
    needed = max(0, target_count - len(PRODUCTS))
    for destination_index, destination in enumerate(DESTINATIONS):
        for template_index, template in enumerate(EXPERIENCE_TEMPLATES):
            if len(generated) >= needed:
                return generated
            focus = destination["focus"][
                (template_index + destination_index) % len(destination["focus"])
            ]
            rng = random.Random(f"{destination['name']}:{focus}:{template['key']}")
            title = f"{focus} {template['title']}"
            price_multiplier = 0.86 + rng.random() * 0.35
            price = int(round(template["price"] * price_multiplier / 10000) * 10000)
            child = int(round(price * (0.58 + rng.random() * 0.12) / 10000) * 10000)
            generated.append(
                {
                    "slug": f"{_slug(destination['name'])}-{_slug(focus)}-{template['key']}",
                    "title": title,
                    "destination": destination["name"],
                    "category": template["category"],
                    "sub": template["sub"],
                    "tags": list(
                        dict.fromkeys(
                            [
                                *template["tags"],
                                *destination["themes"],
                                _slug(focus).replace("-", " "),
                            ]
                        )
                    ),
                    "summary": template["summary"],
                    "description": (
                        f"{template['summary']} This curated {destination['name']} "
                        "experience includes clear meeting instructions, a mobile voucher, "
                        "and practical guidance from a verified local operator."
                    ),
                    "io": template["io"],
                    "duration": template["duration"] + rng.choice([-30, 0, 0, 30]),
                    "price": max(180000, price),
                    "child": max(0, child),
                    "times": template["times"],
                    "rating": round(4.2 + rng.random() * 0.75, 1),
                    "reviews": rng.randint(28, 1850),
                    "family": template["family"],
                    "access": (
                        ["wheelchair accessible", "accessible restroom", "rest stops"]
                        if template["io"] == "indoor"
                        else ["meeting-point assistance", "rest stops"]
                    ),
                    "lat": destination["lat"] + rng.uniform(-0.055, 0.055),
                    "lon": destination["lon"] + rng.uniform(-0.055, 0.055),
                    "validity": template.get("validity", "FIXED_SLOT"),
                    "image_slug": template["image"],
                }
            )
    return generated


def build_seed_catalog(days: int = 30, target_count: int | None = None) -> list[dict]:
    products: list[dict] = []
    today = date.today()
    requested_count = target_count or int(os.getenv("DEMO_CATALOG_SIZE", "360"))
    sources = [*PRODUCTS, *generated_sources(requested_count)]
    for index, source in enumerate(sources[:requested_count]):
        slug = source["slug"]
        experience_id = stable_id("experience", slug)
        option_id = stable_id("option", slug)
        validity = source.get("validity", "FIXED_SLOT")
        prices = [
            {
                "participant_type": "adult",
                "currency": "VND",
                "amount": source["price"],
                "minimum_age": 13,
                "maximum_age": None,
            },
            {
                "participant_type": "child",
                "currency": "VND",
                "amount": source["child"],
                "minimum_age": 3,
                "maximum_age": 12,
            },
            {
                "participant_type": "infant",
                "currency": "VND",
                "amount": 0,
                "minimum_age": 0,
                "maximum_age": 2,
            },
        ]
        # Real marketplaces do not have uniform supply. Seeding every slot with
        # comfortable capacity made scarcity signalling permanently silent and
        # availability_fit unable to discriminate, so the seed models a demand
        # profile instead: a minority of experiences sell through, a few run
        # limited departures, most are comfortable. Deterministic on the slug so
        # runs stay reproducible.
        profile = int(stable_id("demand", slug).int % 100)
        if profile < 12:
            capacity_total, base_remaining = 12, 2  # in demand
        elif profile < 22:
            capacity_total, base_remaining = 8, 4  # small-group format
        else:
            capacity_total, base_remaining = 18, 12
        # Limited-departure operators do not run every day.
        cadence = 3 if 12 <= profile < 22 else 1

        slots = []
        for day_offset in range(1, days + 1):
            if (day_offset + index) % cadence:
                continue
            for hour in source["times"]:
                starts = datetime.combine(today + timedelta(days=day_offset), time(hour), UTC)
                remaining = base_remaining + ((index + day_offset + hour) % 5)
                slots.append(
                    {
                        "id": stable_id("slot", f"{slug}:{starts.isoformat()}"),
                        "starts_at": starts,
                        "ends_at": starts + timedelta(minutes=source["duration"]),
                        "capacity_total": capacity_total,
                        "capacity_remaining": min(remaining, capacity_total),
                        "status": "AVAILABLE",
                    }
                )
        products.append(
            {
                "id": experience_id,
                "external_id": f"VN-{index + 1:03d}",
                "slug": slug,
                "title": source["title"],
                "short_description": source["summary"],
                "description": source["description"],
                "destination": source["destination"],
                "destination_id": stable_id("destination", source["destination"].casefold()),
                "category": source["category"],
                "subcategories": source["sub"],
                "interest_tags": source["tags"],
                "indoor_outdoor": source["io"],
                "duration_minutes": source["duration"],
                "latitude": source["lat"],
                "longitude": source["lon"],
                "meeting_point": f"Confirmed meeting point in {source['destination']} shown on voucher.",
                "languages": ["English", "Vietnamese"],
                "accessibility_features": source["access"],
                "minimum_age": None,
                "family_friendly": source["family"],
                "instant_confirmation": True,
                "mobile_voucher": True,
                "rating": source["rating"],
                "review_count": source["reviews"],
                "popularity_score": min(1.0, 0.35 + source["reviews"] / 1400),
                "status": "PUBLISHED",
                "image_url": (
                    f"/assets/catalog/"
                    f"{source.get('image_slug', IMAGE_SLUGS.get(slug, 'hoi-an-lantern-evening'))}"
                    ".webp"
                ),
                "options": [
                    {
                        "id": option_id,
                        "external_id": f"{slug}-standard",
                        "name": "Standard experience",
                        "description": "Includes all activities and inclusions described for this experience.",
                        "validity_type": validity,
                        "confirmation_type": "INSTANT",
                        "cancellation_policy_code": "FREE_24H",
                        "free_cancellation_hours": 24,
                        "max_party_size": 10,
                        "active": True,
                        "prices": prices,
                        "slots": slots,
                    }
                ],
            }
        )
    return products
